apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: argocdd
  name: argocdd
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: argocdd
    weight: 100
